In [1]:
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd
import csv

In [2]:
url = 'https://raw.githubusercontent.com/jorge3ie/DAT8_Class/master/ier_n.csv'

In [3]:
data = pd.read_csv(url)

In [4]:
X = data.Title
y = data.label

In [5]:
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)
print X_train.shape
print X_test.shape

(9889,)
(3297,)


In [6]:
vect = CountVectorizer(encoding='utf-8', decode_error='ignore', strip_accents='ascii')

In [7]:
vect.fit(X_train)
X_train_dtm = vect.transform(X_train)
X_train_dtm

<9889x13840 sparse matrix of type '<type 'numpy.int64'>'
	with 129585 stored elements in Compressed Sparse Row format>

In [8]:
X_test_dtm = vect.transform(X_test)
X_test_dtm

<3297x13840 sparse matrix of type '<type 'numpy.int64'>'
	with 40744 stored elements in Compressed Sparse Row format>

In [9]:
X_train_tokens = vect.get_feature_names()

In [10]:
print X_train_tokens[:50]

[u'00', u'000', u'00036', u'00091', u'002', u'0029', u'006', u'007', u'007r', u'01', u'010', u'011', u'0131', u'014', u'017', u'01bp', u'01br', u'02', u'020', u'021', u'026', u'028', u'03', u'032', u'04', u'040', u'043', u'0438', u'0452', u'045n', u'0463_', u'049n', u'05', u'052', u'0568', u'057', u'060', u'061', u'061r', u'07', u'072r', u'075', u'079n', u'08', u'087n', u'09', u'0952', u'095n', u'0_3', u'0x7f4ab02fcbf0']


In [11]:
print X_train_tokens[-50:]

[u'yojana', u'york', u'you', u'young', u'younger', u'your', u'youth', u'youths', u'yttrium', u'yugoslav', u'yungas', u'yungas_', u'yunnan', u'zagreb', u'zahle', u'zaire', u'zaire_', u'zambia', u'zambia_', u'zambian', u'zamiba_', u'zamstar', u'zanzibar', u'zanzibari', u'zap', u'zea', u'zealand', u'zealand_', u'zebrafish', u'zero', u'zhangjiakou', u'zhejiang', u'zhenxing', u'zhuyu', u'zidon', u'zidovudine', u'zimbabwe', u'zimbabwe_', u'zimbabwean', u'zinc', u'zlatograd', u'zonal', u'zonas', u'zone', u'zones', u'zoonotic', u'zoophthora', u'zugdidi', u'zulu', u'zuo']


In [12]:
X_train_dtm.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ..., 
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [13]:
import numpy as np
X_train_counts = np.sum(X_train_dtm.toarray(), axis=0)
X_train_counts

array([13,  1,  1, ...,  1,  1,  1])

In [14]:
X_train_counts.shape

(13840,)

In [15]:
pd.DataFrame({'token':X_train_tokens, 'count':X_train_counts}).sort('count')

/Users/jorgemirandamontano/anaconda/lib/python2.7/site-packages/IPython/kernel/__main__.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  if __name__ == '__main__':


count          token
13839      1            zuo
5957       1    harvestplus
11249      1         salmon
11250      1     salmonella
11251      1          salon
5953       1        harness
5952       1          harms
5951       1    harmonizing
5950       1  harmonization
11253      1         salted
5947       1        haripur
5946       1       hargeisa
5945       1      hardwoods
5944       1       hardwood
11248      1          salmo
5943       1       hardship
11255      1          salts
5939       1      harbinger
5937       1        harapan
11258      1      salvadors
5934       1        happens
5933       1       happened
5932       1         happen
5930       1         hannai
11259      1        salvage
5928       1          hands
5927       1       handrubs
5926       1       handover
5925       1        handoff
5942       1         harder
...      ...            ...
4890     429       evidence
1117     437         africa
2609     442           care
3182     444      community
1996     476          based
10872    487         report
6843     502   intervention
1380     515       analysis
4000     529    development
10206    534        program
6127     590            hiv
3442     594     controlled
11199    608          rural
12158    662          study
10554    693     randomized
1363     791             an
13686    799           with
5999     843         health
5461     864           from
4876     876     evaluation
1708     933     assessment
12965   1003          trial
6447    1059         impact
12761   1446             to
9082    1753             on
5363    2074            for
12622   5003            the
1392    5330            and
6493    6465             in
9039    8177             of

[13840 rows x 2 columns]

In [16]:
data_ham = data[data.label==0]
data_spam = data[data.label==1]

In [19]:
data_ham

Author  \
0                                                    NaN   
1                                                    NaN   
2                                                    NaN   
3                                                    NaN   
4                                                    NaN   
5                                                    NaN   
6                                                    NaN   
7                                                    NaN   
8                                                    NaN   
9                                                    NaN   
10                                                   NaN   
11                                                   NaN   
12                                                   NaN   
13                                                   NaN   
14                                                   NaN   
15                                                   NaN   
16                                                   NaN   
17                                                   NaN   
18                                                   NaN   
19                                                   NaN   
20                                                   NaN   
21                                                   NaN   
22                                                   NaN   
23                                                   NaN   
24                                                   NaN   
25                                                   NaN   
26                                                   NaN   
27                                                   NaN   
28                                                   NaN   
29                                                   NaN   
...                                                  ...   
10766                                        D. A. Wirth   
10767                                           D. Atkin   
10768                         S. Joshi and T. P. Schultz   
10769  D. L. Shelton, L. A. Kimball, M. Wagner and R....   
10770                                    B. Essama-Nssah   
10771                                 A. U. P. Education   
10772                                           R. Aijaz   
10773                                 M. S. Chandakavate   
10774                                         S. S. Raju   
10775                                       A. Podhorsky   
10776          S. S. Boocock, W. S. Barnett and E. Frede   
10777                    S. A. Kidd and R. M. C. Liborio   
10778                             M. Garcia and J. Fares   
10779                                       A. S. Mlambo   
10780  L. Prlic, Z. Ebling, K. Glavina, R. Gmajnic, G...   
10781                      M. Jakovljevic and R. Vauhnik   
10782  A. Ivankovi_, J. Ravlija, H. _kobi_, I. Vasilj...   
10783    D. Petek, N. Kern, M. Kovac-Blaz and J. Kersnik   
10784                                          M. Geiger   
10785      A. Steckelberg, I. M�hlhauser and M. Albrecht   
10786                                            D. L�ck   
10787                                           P. Urban   
10788                       A. H. S. Rad and A. Abbasian   
10789                      E. F. Zvobgo and E. F. Zvobgo   
10790  M. Kikuti, I. A. D. Paploski, M. d. C. P. Silv...   
10791  F. M. Baptista, L. Alban, L. R. Nielsen, I. Do...   
10792  A. Comin, J. A. Stegeman, D. Klinkenberg, L. B...   
10793  M. Her, D. H. Cho, S. I. Kang, J. S. Lim, H. J...   
10794                                                NaN   
10795                                           L. Fatty   

                                                   Title  label  
0      _Come Gather Around Together_: An Examination ...      0  
1      A Discussion of impact evaluation results and ...      0  
2      A Methodology for Evaluating Complex Developme...      0  
3      A National evaluation of Safe Schools/Healthy ...      0  

In [20]:
vect.fit(data.Title)
all_tokens = vect.get_feature_names()

In [21]:
all_tokens

[u'00',
 u'000',
 u'00036',
 u'00091',
 u'001',
 u'00103',
 u'002',
 u'0029',
 u'006',
 u'007',
 u'007r',
 u'01',
 u'010',
 u'011',
 u'0131',
 u'014',
 u'017',
 u'01bp',
 u'01br',
 u'02',
 u'020',
 u'021',
 u'023',
 u'026',
 u'028',
 u'0281',
 u'029n',
 u'03',
 u'032',
 u'035r',
 u'0368',
 u'04',
 u'040',
 u'043',
 u'0438',
 u'0452',
 u'045n',
 u'0463_',
 u'049n',
 u'05',
 u'050n',
 u'052',
 u'054',
 u'055',
 u'0568',
 u'057',
 u'060',
 u'061',
 u'061r',
 u'0620',
 u'07',
 u'072r',
 u'075',
 u'076',
 u'079n',
 u'08',
 u'087n',
 u'09',
 u'0952',
 u'095n',
 u'0_3',
 u'0x7f4ab02fcbf0',
 u'10',
 u'100',
 u'1000',
 u'100economic',
 u'1014',
 u'102',
 u'103',
 u'104',
 u'106',
 u'107',
 u'109',
 u'10th',
 u'11',
 u'110',
 u'111',
 u'112',
 u'114',
 u'1141',
 u'115',
 u'117',
 u'118',
 u'119',
 u'11th',
 u'12',
 u'120',
 u'1204',
 u'121',
 u'12174',
 u'123',
 u'126',
 u'1265',
 u'128',
 u'12_13',
 u'12_month',
 u'12th',
 u'13',
 u'130',
 u'131',
 u'133',
 u'134',
 u'135',
 u'136',
 u'137',
 u

In [22]:
ham_dtm = vect.transform(data_ham.Title)
spam_dtm = vect.transform(data_spam.Title)

In [23]:
ham_counts = np.sum(ham_dtm.toarray(), axis=0)

In [24]:
spam_counts = np.sum(spam_dtm.toarray(), axis=0)

In [25]:
token_counts = pd.DataFrame({'token':all_tokens, 'ham':ham_counts, 'spam':spam_counts})

In [26]:
token_counts['ham'] = token_counts.ham + 1
token_counts['spam'] = token_counts.spam + 1

In [30]:
token_counts['spam_ratio'] = token_counts.spam / token_counts.ham
token_counts.sort('spam_ratio')

/Users/jorgemirandamontano/anaconda/lib/python2.7/site-packages/IPython/kernel/__main__.py:2: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  from IPython.kernel.zmq import kernelapp as app


ham  spam          token  spam_ratio
10946  173     1          paper    0.005780
12690  163     1        report_    0.006135
2076   160     1    assessment_    0.006250
12868  276     2         review    0.007246
6685   110     1         global    0.009091
11663   88     1             pp    0.011364
15285   86     1             uk    0.011628
15743   76     1         volume    0.013158
7525    68     1            ill    0.014706
6597    65     1        genetic    0.015385
4270    62     1     critically    0.016129
15165   59     1       tropical    0.016949
13905   57     1        species    0.017544
8203   112     2         issues    0.017857
13787   54     1        society    0.018519
15482  107     2          usaid    0.018692
13578   53     1          shock    0.018868
11938   53     1       progress    0.018868
4367    53     1        current    0.018868
10442   50     1            nri    0.020000
7467    47     1            icu    0.021277
15392   47     1         united    0.021277
7903    91     2      institute    0.021978
13435   45     1         septic    0.022222
6200    90     2      fisheries    0.022222
2600    45     1   biodiversity    0.022222
12689  629    14         report    0.022258
4233    44     1           cprc    0.022727
11236   43     1   perspectives    0.023256
3225    43     1           cbms    0.023256
...    ...   ...            ...         ...
7744     1     4     indonesias    4.000000
9592     1     4         midday    4.000000
6275     1     4       flypaper    4.000000
15498    1     4          usual    4.000000
11937    7    30       progresa    4.285714
13969    2     9       spraying    4.500000
15807    2     9        washing    4.500000
10549    1     5         ocular    5.000000
11896    3    15     productive    5.000000
15985    1     5       workfare    5.000000
12131    1     5          pupil    5.000000
6159     1     5     filtration    5.000000
9823     1     5        monthly    5.000000
9393     1     5      mediation    5.000000
6933     1     5    haemoglobin    5.000000
14878    1     5        titling    5.000000
13757    1     5            sms    5.000000
14732    1     5  the_impact_of    5.000000
3565     1     5      cleansing    5.000000
10660    3    17  oportunidades    5.666667
12644    1     6      reminders    6.000000
2467     3    18        bednets    6.000000
13820    1     6      solidario    6.000000
4627     2    12         dengue    6.000000
9355     1     6           meal    6.000000
9525     1     7        mexicos    7.000000
7878     1     7   insecticidal    7.000000
11654    1     8         powder    8.000000
3293     1     8        ceramic    8.000000
4893     1     8  discontinuity    8.000000

[16144 rows x 4 columns]

In [28]:
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB()
nb.fit(X_train_dtm, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [29]:
y_pred_class = nb.predict(X_test_dtm)

In [31]:
from sklearn import metrics
print metrics.accuracy_score(y_test, y_pred_class)

0.879890809827


In [32]:
print metrics.confusion_matrix(y_test, y_pred_class)

[[2520  197]
 [ 199  381]]


In [33]:
y_pred_prob = nb.predict_proba(X_test_dtm)[:, 1]
y_pred_prob

array([  1.25242230e-02,   3.69046849e-01,   9.89354588e-01, ...,
         5.01886159e-04,   3.54115835e-04,   4.27982426e-01])

In [34]:
print metrics.roc_auc_score(y_test, y_pred_prob)

0.903474293402


In [35]:
X_test[y_test < y_pred_class]

5022    A Quasi-Experimental Evaluation of Students Ag...
4796    Development of an opinion leader-led HIV preve...
5424    Long-term consequences of iron-fortified flour...
7312    Can Conditional Cash Transfers Contribute to R...
7707    Tackling tuberculosis patients' internalized s...
4379    The potential impact of community-based distri...
335     The Effect of ILO Minimum Age Conventions on C...
5260    Cost-effectiveness of home-based chlorination ...
8791    Impact of intermittent preventive treatment wi...
223     Labor Market Returns to Education in Mozambiqu...
5284    Drinking Water Quality, Feeding Practices, and...
5287    Zinc and iron supplementation and malaria, dia...
8540    A randomized control trial of an Ultra-Short z...
115     Evaluating the Long-term Impact of Antipoverty...
8709    Effect of relaxation training on psychosomatic...
394     Water , Sanitation and Children _ s Health Evi...
222     Labor market discrimination in Delhi: Evidence...
316     Techni

In [36]:
X_test[y_test > y_pred_class]

11692    Impact Evaluation of a Rural Road Rehabilitati...
11062    Welfare Grants and Their Impact on Child Healt...
13093    Family Planning and Women's and Children's Hea...
11160    Water Expansions in Shantytowns: Health and Sa...
11001    An Impact Evaluation of India's Second and Thi...
11019    Enhancing Income Opportunities for the Rural P...
11076    Chlorhexidine Maternal-Vaginal and Neonate Bod...
11109    How Do Additional Alternatives Affect Individu...
12630    Evaluation of Back to Basics Mathematics Workb...
12783        An Impact Evaluation of the MIDA FBO Training
11688    Effectiveness and Efficacy of Zinc for the Tre...
11801    The Effects of Infrastructure Development on G...
12548    Beneath the �Methods Debate� in_Impact_Assessm...
11312    Environmental and Gender Impacts of Land Tenur...
12480    Quantitative Assessment of a Tanzanian Integra...
12049    Stratification and Public Utility Services in ...
12166    Young Citizens as Health Agents: Use of Drama .

In [37]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression(C=1e9)
logreg.fit(X_train_dtm, y_train)

LogisticRegression(C=1000000000.0, class_weight=None, dual=False,
          fit_intercept=True, intercept_scaling=1, max_iter=100,
          multi_class='ovr', penalty='l2', random_state=None,
          solver='liblinear', tol=0.0001, verbose=0)

In [38]:
y_pred_class = logreg.predict(X_test_dtm)
y_pred_prob = logreg.predict_proba(X_test_dtm)[:, 1]

In [39]:
print metrics.accuracy_score(y_test, y_pred_class)

0.84652714589


In [40]:
print metrics.roc_auc_score(y_test, y_pred_prob)

0.827132803675
